### ISSUE TITLE
Can you please upload a README file ? 

### ISSUE THREAD

**Issue by senthilki** [anthonytw/Random-Forest#1]
1. Commands to execute the code ?

**Comment by anthonytw** [comment]
@senthilki It might be worth looking at this implementation instead: https://github.com/anthonytw/Random-Forest-MPI. It was a while ago that I worked on this before switching to the MPI implementation, it might be missing some bug fixes.

My "resolution" to this will be to archive this repository, since I don't maintain it anymore. :-)
